// Generated by CoffeeScript 1.7.1
(function() {
  var focusable;

  $(function() {
    var getContent;
    getContent = function(file) {
      $.get("" + file + ".html", function(data) {
        $('main').removeClass("offscreen");
        $('main').html(data);
        return focusable(".field, input, textarea");
      });
      $("menu > .active.item").removeClass('active');
      $("[data-content='" + file + "']").addClass('active');
      return window.location.replace("#" + file);
    };
    $('aside > menu > .item').click(function() {
      var content;
      content = $(this).attr("data-content");
      $('aside').removeClass("center-aside");
      $("menu > .active.item").removeClass('active');
      $("[data-content='" + content + "']").addClass('active');
      return getContent($(this).attr("data-content"));
    });
    $('aside > .logo').click(function() {
      $('aside').addClass("center-aside");
      $('main').addClass("offscreen");
      $("menu > .active.item").removeClass('active');
      window.location.replace("#");
      console.log($('aside .logo').height());
      if ($('aside').hasClass("small")) {
        $('aside').removeClass("small");
        return $('aside > menu').slideDown();
      }
    });
    if (window.location.hash) {
      $('aside').removeClass("center-aside small");
      $('aside > menu').slideDown();
      return getContent(window.location.hash.substr(1));
    }
  });

  focusable = function(selector) {
    $(selector).focus(function() {
      $(".field").removeClass("focused");
      return $(this).parent(".field").addClass("focused");
    });
    return $(selector).blur(function() {
      return $(".field").removeClass("focused");
    });
  };

}).call(this);
